export interface RoleSpecificQuestions {
  [relationshipType: string]: {
    [role: string]: string[];
  };
}

export const roleSpecificQuestions: RoleSpecificQuestions = {
  "Parent-Child": {
    "Father": [
      "What mistake did I make as a father that I wish I could apologize for or explain?",
      "What fear do I have about our relationship that I've never voiced?",
      "How did my own father's parenting affect me in ways I might have passed on to you?",
      "What aspect of your adult life makes me worry about you most, and why?",
      "What's something I'm struggling with personally that I think you should know about?",
      "When have I felt most proud of you in a way I never properly expressed?",
      "What conversation have I been avoiding having with you because it feels too difficult?",
      "How has watching you become an adult forced me to confront my own mortality or aging?",
      "What do I wish I had done differently during your childhood that still weighs on me?",
      "What aspect of my own character or past do I hope you understand rather than judge?",
      "What moment from your childhood do I remember differently than you might?",
      "What family tradition or value did I fail to pass on that I regret?",
      "What's the hardest thing about being your father that I've never admitted?",
      "What do I wish I could protect you from that I know I can't?",
      "What lesson did I try to teach you that I'm not sure you understood?",
      "What part of my own upbringing do I wish had been different for your sake?",
      "What sacrifice did I make for our family that went unnoticed?",
      "What dream did I give up when I became a father, and how do I feel about that now?",
      "What's something about being a man that I never taught you but should have?",
      "What moment of your childhood fills me with the deepest regret?",
      "What strength do you have that I wish I had developed myself?",
      "What fear do I have about our future relationship as you continue to grow?",
      "What part of myself do I see in you that both excites and worries me?",
      "What conversation about money, success, or life priorities should we have had sooner?",
      "What's the most important thing I want you to remember about me after I'm gone?",
      "What aspect of modern parenting or the world today confuses or scares me?",
      "What moment made me realize I didn't know how to be the father you needed?",
      "What's something I'm still learning about fatherhood even now?",
      "What do I wish my own father had told me that I want to tell you?",
      "What's the biggest lie or misconception about me that I want to clear up?",
      "What part of your personality challenges me as a parent in ways I haven't shared?",
      "What decision did I make for our family that I question now?",
      "What's something about your mother and my relationship that affects how I parent?",
      "What expectation did I have of fatherhood that was completely wrong?",
      "What moment of connection between us do I treasure most?",
      "What's something I need to forgive myself for as your father?",
      "What advice did I give you that I'm no longer sure was right?",
      "What part of my job or career affected our relationship in ways you might not know?",
      "What's the hardest thing about watching you become independent?",
      "What do I admire about you that I've never properly acknowledged?",
      "What family pattern or cycle am I afraid we might be repeating?",
      "What's something about my own father's death or aging that affects how I parent?",
      "What moment made me realize you were no longer a child?",
      "What's the biggest challenge I face in relating to you as an adult?",
      "What part of your childhood do I wish I could re-do completely?",
      "What's something I learned too late to help you with when you needed it?",
      "What do I worry about in terms of the world you're inheriting?",
      "What's the most profound way that being your father changed me?",
      "What conversation about relationships, love, or intimacy feels overdue?",
      "What's something about my own struggles with masculinity that I think you should know?",
      "What moment of your success or achievement meant more to me than you realized?",
      "What's the hardest truth about life that I've been reluctant to share with you?",
      "What part of my personality or character do I hope you don't inherit?",
      "What's something I need from you as my child that I don't know how to ask for?",
      "What legacy or impact do I hope to have had on your life?",
      "What's the biggest risk I took as a father that I'm not sure paid off?",
      "What conversation about failure, disappointment, or resilience should we have?",
      "What's something about my own mental health or emotional struggles that affects our relationship?",
      "What moment of your independence both proud and scared me?",
      "What's the most important lesson about life that I hope I've taught you?",
      "What part of being your father has been the most surprising or unexpected?",
      "What do I wish I understood better about your generation or your perspective?",
      "What's something about our family history or story that you should know but don't?",
      "What moment of conflict between us taught me something important about you?",
      "What's the biggest way that you've exceeded my expectations or hopes?",
      "What conversation about purpose, meaning, or spirituality feels important but difficult?",
      "What's something I need to let go of in order to have a better relationship with you?",
      "What part of my own father's absence or presence still affects how I parent?",
      "What's the most vulnerable I've ever felt as your father?",
      "What do I hope you'll understand about my generation that seems lost on yours?",
      "What's something about my marriage or relationships that I think impacts you?",
      "What moment made me realize I had become the kind of father I wanted to be?",
      "What's the biggest regret I have about our relationship that we've never discussed?",
      "What do I wish I could go back and tell you during your most difficult moments?",
      "What's something about my own dreams or ambitions that I want you to know?",
      "What part of watching you grow up has been the most difficult to accept?",
      "What's the most important conversation we need to have before it's too late?"
    ],
    "Mother": [
      "What fear about motherhood or my parenting do I carry that I've never shared with you?",
      "What sacrifice I made for our family do I sometimes resent, and how has that affected me?",
      "When did I feel most lost or overwhelmed as your mother, and what did I learn from that?",
      "What part of my own mother's parenting do I see reflected in myself that worries me?",
      "What aspect of your adult life triggers my deepest maternal anxieties?",
      "What moment of your childhood do I wish I could have handled completely differently?",
      "What's something about my own struggles with womanhood that I think you should understand?",
      "How has my relationship with your father affected you in ways I'm afraid to acknowledge?",
      "What conversation about family, relationships, or life have I been too scared to start with you?",
      "What do I need from our adult relationship that I don't know how to ask for?",
      "What's the hardest thing about being your mother that I've never admitted?",
      "What moment made me question if I was cut out for motherhood?",
      "What part of my identity did I lose when I became a mother that I'm still grieving?",
      "What's something I wish I could undo or redo from your early years?",
      "What fear do I have about your future that keeps me awake at night?",
      "What aspect of my own childhood affects how I mother you?",
      "What's the biggest mistake I made as your mother that we've never discussed?",
      "What do I wish I had known about motherhood before I became one?",
      "What part of your personality challenges me in ways I haven't shared?",
      "What's something about my marriage that impacts how I parent?",
      "What expectation of motherhood turned out to be completely wrong?",
      "What moment of your independence both excited and terrified me?",
      "What's something I need to forgive myself for as your mother?",
      "What conversation about womanhood, relationships, or life feels overdue?",
      "What pattern from my own mother am I afraid I've repeated with you?",
      "What's the most vulnerable I've ever felt as your mother?",
      "What do I admire about you that I've never properly expressed?",
      "What's something about my own mental health that affects our relationship?",
      "What moment made me realize you were becoming your own person?",
      "What's the biggest way motherhood has changed me that you might not see?",
      "What advice did I give you that I'm no longer sure was right?",
      "What's something about my own mother's absence or presence that shapes how I parent?",
      "What family tradition or value did I fail to pass on that I regret?",
      "What's the hardest lesson about life I've had to teach you?",
      "What moment of your childhood fills me with the deepest pride?",
      "What's something I learned too late to help you when you needed it most?",
      "What do I worry about in terms of the world you're growing up in?",
      "What's the most important thing I want you to remember about our relationship?",
      "What part of being a woman that I wish I had prepared you better for?",
      "What's something about my career or dreams that affected how I mothered?",
      "What moment taught me something profound about who you are?",
      "What's the biggest challenge I face in letting you make your own mistakes?",
      "What conversation about my own struggles or failures should we have?",
      "What's something I need from you as my child that feels too needy to ask for?",
      "What legacy do I hope to leave you as your mother?",
      "What's the most surprising thing about watching you grow up?",
      "What do I wish my own mother had told me that I want to tell you?",
      "What's something about our family dynamics that you should understand?",
      "What moment made me realize I had become the mother I wanted to be?",
      "What's the biggest risk I took as a mother that I'm not sure paid off?",
      "What part of your father do I see in you that both delights and worries me?",
      "What's something about my own upbringing that I've tried to do differently?",
      "What moment of conflict between us taught me something important?",
      "What's the hardest truth about life that I've been reluctant to share?",
      "What do I hope you'll understand about my generation that seems lost on yours?",
      "What's something about my marriage or relationships that I think impacts you?",
      "What conversation about failure, resilience, or disappointment should we have?",
      "What's the biggest way you've exceeded my hopes and expectations?",
      "What part of my personality do I hope you don't inherit?",
      "What's something I'm still learning about motherhood even now?",
      "What moment made me realize you no longer needed me in the same way?",
      "What's the most difficult part of watching you become independent?",
      "What do I wish I understood better about your perspective or generation?",
      "What's something about our family history that you should know but don't?",
      "What sacrifice did I make that went unnoticed but shaped our family?",
      "What's the biggest misconception about me that I want to clear up?",
      "What moment of your success meant more to me than you realized?",
      "What's something I need to let go of to have a better relationship with you?",
      "What conversation about purpose, spirituality, or meaning feels important?",
      "What's the hardest part of being the kind of mother I want to be?",
      "What do I worry about most regarding your emotional or mental health?",
      "What's something about my own emotional struggles that affects how I parent?",
      "What moment made me most proud to be your mother?",
      "What's the biggest regret I have about our relationship that we've never discussed?",
      "What do I wish I could go back and tell you during your most difficult times?",
      "What's something about my dreams or ambitions that I want you to understand?",
      "What part of watching you grow up has been the most difficult to accept?",
      "What's the most important conversation we need to have before it's too late?"
    ],
    "Son": [
      "What do I struggle with as a man that I'm afraid to admit to you?",
      "How did your parenting affect my confidence or self-worth in ways you might not realize?",
      "What aspect of my adult life do I feel like I'm failing at that I need your perspective on?",
      "What fear do I have about becoming like you, or not living up to your expectations?",
      "What's something about my relationships or choices that I've been afraid to tell you?",
      "How do I deal with pressure to be 'successful' when I'm not sure what that means anymore?",
      "What part of your past or your struggles do I need to understand to know you better as a person?",
      "What conversation between us feels overdue but too difficult to start?",
      "How do I handle feeling like I've disappointed you, even when you haven't said so?",
      "What do I need to know about your own failures or regrets to feel less alone in mine?",
      "What's the biggest challenge I face as a man that I wish you understood better?",
      "What moment from my childhood still affects how I see myself today?",
      "What's something about masculinity or being a man that confuses or troubles me?",
      "What fear do I have about my future that I've never shared with you?",
      "What's the hardest thing about trying to make you proud while being true to myself?",
      "What aspect of your relationship with mom affected how I view relationships?",
      "What's something I admire about you that I've never told you?",
      "What lesson you tried to teach me am I finally starting to understand?",
      "What's the biggest way I feel different from you, and how does that affect our relationship?",
      "What conversation about mental health, emotions, or vulnerability feels overdue?",
      "What's something about my career or life path that I need your honest opinion on?",
      "What fear do I have about repeating your mistakes or falling short of your example?",
      "What's the most insecure I feel when I compare myself to you or your generation?",
      "What aspect of my personality do you not understand that I wish you did?",
      "What's something about my childhood that you remember differently than I do?",
      "What advice did you give me that I dismissed but now think was right?",
      "What's the biggest challenge I face in relationships that I need your perspective on?",
      "What part of growing up in our family do I need to make peace with?",
      "What's something about my generation that you should understand about me?",
      "What conversation about money, success, or priorities should we have had sooner?",
      "What's the hardest truth about life that I'm still learning to accept?",
      "What moment made you realize I was becoming my own person rather than just your son?",
      "What's something I need to forgive you for that we've never discussed?",
      "What pattern from our family am I afraid I might repeat in my own life?",
      "What's the biggest risk I'm taking in my life that I need your support with?",
      "What aspect of your marriage or relationship choices should I learn from?",
      "What's something about my mental health or emotional struggles that affects our relationship?",
      "What conversation about failure, disappointment, or resilience feels important?",
      "What's the most important thing you want me to know about being a man?",
      "What fear do I have about our relationship changing as we both get older?",
      "What's something I need from you as my father/mother that I don't know how to ask for?",
      "What moment of independence or growth made you most proud of me?",
      "What's the biggest way I've surprised you or exceeded your expectations?",
      "What conversation about purpose, meaning, or spirituality feels overdue?",
      "What's something about my childhood that I wish had been different?",
      "What aspect of your own upbringing do you see affecting how you raised me?",
      "What's the hardest thing about watching me make my own mistakes?",
      "What do I need to understand about your sacrifices or struggles for our family?",
      "What's something about my friendships or social life that concerns you?",
      "What conversation about love, intimacy, or relationships feels difficult but important?",
      "What's the biggest misconception I might have about you that you want to correct?",
      "What moment taught you something important about who I am as a person?",
      "What's something about our family history or story that I should know but don't?",
      "What fear do you have about my future that I should take seriously?",
      "What's the most vulnerable you've ever been willing to be with me?",
      "What conversation about your own mistakes or regrets would help me understand you better?",
      "What's something I inherited from you that both worries and pleases you?",
      "What moment of conflict between us taught you something about our relationship?",
      "What's the biggest challenge you face in relating to me as an adult?",
      "What conversation about legacy, family, or what matters most feels important?",
      "What's something about your dreams or ambitions that you want me to understand?",
      "What do you wish you could go back and tell me during my most difficult times?",
      "What's the most important lesson about life that you hope you've taught me?",
      "What part of your personality or character do you hope I've inherited?",
      "What's something you need to let go of in order to have a better relationship with me?",
      "What conversation we need to have before it's too late?"
    ],
    "Daughter": [
      "What do I struggle with as a woman that I'm embarrassed to ask you about?",
      "How did growing up in our family affect my self-image or confidence in ways you might not see?",
      "What pattern from your life am I repeating that I don't want to continue?",
      "What fear do I have about my relationships or future that I need your honest insight on?",
      "What aspect of your marriage or relationship choices do I need to understand better?",
      "How do I handle the pressure of being a 'good daughter' while living my own life?",
      "What sacrifice or struggle of yours do I take for granted that I should acknowledge?",
      "What conversation about womanhood, family, or expectations feels too vulnerable to have?",
      "How do I deal with feeling like I can't live up to your strength or what you've accomplished?",
      "What do I need to know about your mistakes or regrets to feel less afraid of making my own?",
      "What's the biggest challenge I face as a woman that I wish you understood better?",
      "What moment from my childhood still shapes how I see myself today?",
      "What's something about being a woman that scares or confuses me?",
      "What fear do I have about my future relationships or career that I've never shared?",
      "What's the hardest thing about trying to make you proud while being true to myself?",
      "What aspect of your relationship with dad affected how I view love and relationships?",
      "What's something I admire about you that I've never properly expressed?",
      "What lesson you tried to teach me am I finally starting to understand?",
      "What's the biggest way I feel different from you, and how does that affect us?",
      "What conversation about body image, sexuality, or self-worth feels overdue?",
      "What's something about my career or life choices that I need your honest opinion on?",
      "What fear do I have about repeating your struggles or not living up to your example?",
      "What's the most insecure I feel when I compare myself to you or your generation?",
      "What aspect of my personality do you not understand that I wish you did?",
      "What's something about my childhood that you remember differently than I do?",
      "What advice did you give me that I rejected but now think was wise?",
      "What's the biggest challenge I face in relationships that I need your perspective on?",
      "What part of growing up in our family do I need to make peace with?",
      "What's something about my generation that you should understand about me?",
      "What conversation about motherhood, family, or life priorities should we have had sooner?",
      "What's the hardest truth about being a woman that I'm still learning to accept?",
      "What moment made you realize I was becoming my own woman rather than just your daughter?",
      "What's something I need to forgive you for that we've never discussed?",
      "What pattern from our family am I afraid I might repeat in my own life?",
      "What's the biggest risk I'm taking in my life that I need your support with?",
      "What aspect of your marriage or relationship should I learn from?",
      "What's something about my mental health or emotional struggles that affects our relationship?",
      "What conversation about independence, boundaries, or self-advocacy feels important?",
      "What's the most important thing you want me to know about being a woman?",
      "What fear do I have about our relationship changing as we both get older?",
      "What's something I need from you as my mother/father that I don't know how to ask for?",
      "What moment of independence or growth made you most proud of me?",
      "What's the biggest way I've surprised you or exceeded your expectations?",
      "What conversation about purpose, spirituality, or what matters most feels overdue?",
      "What's something about my childhood that I wish had been different?",
      "What aspect of your own upbringing do you see affecting how you raised me?",
      "What's the hardest thing about watching me make my own mistakes?",
      "What do I need to understand about your sacrifices or struggles for our family?",
      "What's something about my friendships or social life that concerns you?",
      "What conversation about love, intimacy, or what I deserve in relationships feels difficult but important?",
      "What's the biggest misconception I might have about you that you want to correct?",
      "What moment taught you something important about who I am as a person?",
      "What's something about our family history or story that I should know but don't?",
      "What fear do you have about my future that I should take seriously?",
      "What's the most vulnerable you've ever been willing to be with me?",
      "What conversation about your own mistakes or regrets would help me understand you better?",
      "What's something I inherited from you that both worries and pleases you?",
      "What moment of conflict between us taught you something about our relationship?",
      "What's the biggest challenge you face in relating to me as an adult woman?",
      "What conversation about legacy, family, or what matters most feels important?",
      "What's something about your dreams or ambitions that you want me to understand?",
      "What do you wish you could go back and tell me during my most difficult times?",
      "What's the most important lesson about life that you hope you've taught me?",
      "What part of your personality or character do you hope I've inherited?",
      "What's something you need to let go of in order to have a better relationship with me?",
      "What conversation do we need to have before it's too late?"
    ]
  },
  "Romantic Partners": {
    "Boyfriend": [
      "What fear do I have about our relationship that I haven't shared with you?",
      "What part of my past still affects how I love you that you should know about?",
      "What do I need from you emotionally that I'm afraid to ask for?",
      "What insecurity do I have about myself in our relationship?",
      "What conversation about our future scares me but feels necessary?",
      "How do I handle my feelings when I think you might be losing interest?",
      "What aspect of physical or emotional intimacy do I struggle with but haven't discussed?",
      "What do I compare our relationship to that might be unfair or harmful?",
      "What sacrifice would I be willing to make for you that you don't know about?",
      "What doubt about us do I have that I wish you could help me resolve?"
    ],
    "Girlfriend": [
      "What vulnerability about myself am I afraid to show you?",
      "What part of love or relationships confuses or scares me that I need your patience with?",
      "What do I need to feel secure with you that I haven't been able to express?",
      "What fear do I have about losing myself in this relationship?",
      "What conversation about commitment or our future feels too scary to start?",
      "How do I handle feeling jealous or insecure in ways that might hurt us?",
      "What expectation do I have of you that might be unfair but feels important to me?",
      "What part of my emotional needs feels too needy or demanding to share?",
      "What do I struggle with physically or emotionally that affects our intimacy?",
      "What doubt or fear about love do I carry from my past that impacts how I love you?"
    ],
    "Husband": [
      "What part of marriage do I struggle with that I haven't admitted to you?",
      "What fear do I have about our future together that keeps me awake at night?",
      "What sacrifice or compromise in our marriage do I sometimes resent?",
      "What aspect of our physical or emotional intimacy needs honest discussion?",
      "What expectation of marriage or partnership am I failing to meet?",
      "What conversation about money, family, or life goals have I been avoiding?",
      "How do I handle feeling disconnected from you when life gets overwhelming?",
      "What part of my identity or dreams do I feel like I've lost in our marriage?",
      "What do I need from you as my wife that I don't know how to ask for?",
      "What regret or mistake in our relationship do I need to acknowledge and address?"
    ],
    "Wife": [
      "What need do I have in our marriage that I've been afraid to voice?",
      "What fear about our relationship or future do I carry alone?",
      "What part of being a wife feels overwhelming or unclear to me?",
      "What conversation about intimacy, expectations, or boundaries feels overdue?",
      "What sacrifice I've made for our marriage do I need you to understand?",
      "How do I handle feeling unappreciated or misunderstood in our relationship?",
      "What aspect of our partnership makes me feel lonely even when we're together?",
      "What do I struggle with about balancing my individual identity with being your wife?",
      "What expectation or dream about marriage has been harder than I expected?",
      "What conversation about our emotional or physical connection feels too vulnerable to start?"
    ],
    "Partner": [
      "What's something you love about how we communicate?",
      "How do you feel we complement each other?",
      "What's a goal you'd like us to work toward together?",
      "What makes our relationship unique?",
      "What's your favorite way we spend time together?"
    ],
    "Fiance": [
      "What are you most excited about for our wedding?",
      "How do you imagine our life together after marriage?",
      "What's something you're looking forward to sharing as spouses?",
      "What traditions do you want to start together?",
      "What made you know you wanted to marry me?"
    ],
    "Fiancee": [
      "What are you most excited about for our wedding?",
      "How do you imagine our life together after marriage?",
      "What's something you're looking forward to sharing as spouses?",
      "What traditions do you want to start together?",
      "What made you know you wanted to marry me?"
    ]
  },
  "Friends": {
    "Best Friend": [
      "What fear do I have about our friendship that I've never admitted?",
      "What part of my life or personality do I hide from you because I'm afraid you'll judge me?",
      "What moment in our friendship did I handle badly that I still feel guilty about?",
      "What do I need from you as my friend that I'm too afraid to ask for?",
      "What jealousy or resentment have I felt toward you that I've kept secret?",
      "What conversation between us feels overdue but too scary to start?",
      "How has our friendship changed me in ways that I haven't acknowledged?",
      "What vulnerability about myself do I wish I could share with you but feel too exposed to?",
      "What assumption about our friendship might be wrong that we should talk about?",
      "What support do I need during difficult times that I don't know how to ask for?",
      "What's the biggest lie I've told you, even if it was by omission?",
      "What moment made me realize how much your friendship means to me?",
      "What's something I've always wanted to ask you but felt too embarrassed?",
      "What pattern in my life do you see that I'm blind to?",
      "What's the most selfish thing I've done in our friendship?",
      "What aspect of your life do I not understand but want to?",
      "What's something about my past that still affects how I act in friendships?",
      "What boundary have I crossed in our friendship that I should acknowledge?",
      "What's the most honest feedback you could give me that I might not want to hear?",
      "What fear do I have about you moving on or outgrowing our friendship?",
      "What's something I pretend to understand about you but actually don't?",
      "What moment of conflict between us taught me something important?",
      "What's the biggest way our friendship has disappointed me that I've never said?",
      "What do I take for granted about you or our friendship?",
      "What's something about my other relationships that you've observed but never commented on?",
      "What part of growing up or changing is affecting our friendship?",
      "What's the most vulnerable I've ever been with you, and how did it feel?",
      "What expectation do I have of our friendship that might be unfair?",
      "What's something about your struggles that I wish I could help with but don't know how?",
      "What moment made you realize we had become true friends?",
      "What's the biggest sacrifice you've made for our friendship?",
      "What's something I do that annoys you but you've never mentioned?",
      "What conversation about the future of our friendship feels important but difficult?",
      "What's the most insecure you've felt in our friendship?",
      "What aspect of my personality do you think I don't see clearly?",
      "What's something about friendship in general that you've learned from our relationship?",
      "What fear do you have about our friendship changing as we get older?",
      "What's the biggest misunderstanding we've had that was never fully resolved?",
      "What do you wish I knew about what it's like to be friends with me?",
      "What's something about my family or background that affects our friendship?",
      "What moment in our friendship are you most grateful for?",
      "What's the hardest truth about life that we should discuss as friends?",
      "What do you need from me as a friend that you don't know how to ask for?",
      "What's something about my mental health or emotional state that you've noticed?",
      "What pattern in our friendship dynamic might not be healthy?",
      "What's the most important lesson our friendship has taught you?",
      "What conversation about loyalty, trust, or boundaries feels overdue?",
      "What's something about your own struggles with friendship that you want me to understand?",
      "What moment made you question our friendship, even briefly?",
      "What's the biggest way I've grown or changed since we became friends?",
      "What fear about opening up or being vulnerable affects how you relate to me?",
      "What's something about my other friendships that you've wondered about?",
      "What do you wish you could tell me about how to be a better friend?",
      "What's the most meaningful thing I've ever done for you that I might not realize?",
      "What conversation about our different values or beliefs feels important?",
      "What's something about the future that you hope we'll experience together?",
      "What aspect of our friendship do you think other people don't understand?",
      "What's the biggest risk you've taken in our friendship?",
      "What do you hope our friendship will look like in ten years?",
      "What's something you've learned about yourself through our friendship?",
      "What moment of honesty between us was the most difficult but most worthwhile?",
      "What's the most important thing you want me to know about our friendship?"
    ],
    "Close Friend": [
      "What insecurity do I have that affects our friendship that you might not see?",
      "What part of my life do I struggle with that I wish I could get your perspective on?",
      "What fear do I have about growing apart as we change and evolve?",
      "What boundary in our friendship feels unclear or difficult to navigate?",
      "What conversation about our different life paths or choices feels too sensitive?",
      "How do I handle feeling left out or jealous in our friendship?",
      "What expectation do I have of our friendship that might be unfair?",
      "What part of my personality or behavior do I worry might push you away?",
      "What difficult truth about myself do I wish I could share with you?",
      "What do I appreciate about you that I've never properly expressed?"
    ],
    "Friend": [
      "What do I struggle with in friendships that makes me afraid of getting too close?",
      "What part of my life feels too messy or complicated to share with friends?",
      "What fear do I have about being truly known by the people in my life?",
      "What conversation about boundaries or expectations in our friendship feels overdue?",
      "What insecurity do I have about whether people actually enjoy my company?",
      "How do I handle feeling like I give more to friendships than I receive?",
      "What part of my past or current struggles do I keep hidden from friends?",
      "What do I need from friendships that I don't know how to communicate?",
      "What pattern in my relationships do I repeat that might be harmful?",
      "What vulnerability about friendship or connection do I carry that affects how I relate to others?"
    ],
    "Childhood Friend": [
      "What's your favorite childhood memory of us?",
      "How do you think we've both changed since we were kids?",
      "What's something from our childhood that still makes you laugh?",
      "How has our friendship evolved as we've grown up?",
      "What childhood dream of yours do you still think about?"
    ],
    "College Friend": [
      "What's your best memory from our college days?",
      "How do you think college shaped who we are today?",
      "What's something we used to do in college that you miss?",
      "How has our friendship changed since graduation?",
      "What's a college experience you're grateful we shared?"
    ],
    "Work Friend": [
      "What's the best part about having you as a colleague?",
      "How do you think we complement each other professionally?",
      "What's a work challenge you'd like to discuss?",
      "What's your favorite non-work thing we've discovered about each other?",
      "How has working together strengthened our friendship?"
    ]
  },
  "Siblings": {
    "Brother": [
      "What's your favorite childhood memory of us?",
      "How do you think we've influenced each other?",
      "What's something you admire about your sister?",
      "What family trait do you see in both of us?",
      "What's a tradition you hope we continue as adults?"
    ],
    "Sister": [
      "What's your favorite childhood memory of us?",
      "How do you think we've influenced each other?",
      "What's something you admire about your brother?",
      "What family trait do you see in both of us?",
      "What's a tradition you hope we continue as adults?"
    ],
    "Twin Brother": [
      "What's it like having a twin sister?",
      "How do you think being twins has shaped our relationship?",
      "What's something unique about our twin bond?",
      "How are we most similar and most different?",
      "What's your favorite thing about being twins?"
    ],
    "Twin Sister": [
      "What's it like having a twin brother?",
      "How do you think being twins has shaped our relationship?",
      "What's something unique about our twin bond?",
      "How are we most similar and most different?",
      "What's your favorite thing about being twins?"
    ],
    "Older Brother": [
      "What's it like being the big brother?",
      "What's something you hope to teach your younger sibling?",
      "How do you feel about your role in the family?",
      "What's your favorite memory of protecting or helping your sibling?",
      "What advice would you give your younger sibling?"
    ],
    "Older Sister": [
      "What's it like being the big sister?",
      "What's something you hope to teach your younger sibling?",
      "How do you feel about your role in the family?",
      "What's your favorite memory of protecting or helping your sibling?",
      "What advice would you give your younger sibling?"
    ],
    "Younger Brother": [
      "What's it like being the little brother?",
      "What's something you've learned from your older sibling?",
      "How do you feel about your place in the family?",
      "What's your favorite thing about having an older sibling?",
      "What's something you want your older sibling to know?"
    ],
    "Younger Sister": [
      "What's it like being the little sister?",
      "What's something you've learned from your older sibling?",
      "How do you feel about your place in the family?",
      "What's your favorite thing about having an older sibling?",
      "What's something you want your older sibling to know?"
    ]
  },
  "Grandparents": {
    "Grandfather": [
      "What's your favorite story from when you were young?",
      "What's the most important lesson you want to pass down?",
      "How has the world changed since you were my age?",
      "What's your proudest moment as a grandfather?",
      "What tradition from your generation do you hope continues?"
    ],
    "Grandmother": [
      "What's your favorite story from when you were young?",
      "What's the most important lesson you want to pass down?",
      "How has the world changed since you were my age?",
      "What's your proudest moment as a grandmother?",
      "What tradition from your generation do you hope continues?"
    ],
    "Grandparent": [
      "What's something about your childhood you'd like me to know?",
      "What's your favorite memory of our family?",
      "What advice would you give to someone my age?",
      "What's something you're proud of about our family?",
      "What do you hope for my future?"
    ],
    "Grandson": [
      "What's your favorite thing about spending time with grandparents?",
      "What's something you'd like to learn from your grandparent?",
      "What's a family story you'd love to hear more about?",
      "How do you think you're similar to your grandparent?",
      "What's something you want to thank your grandparent for?"
    ],
    "Granddaughter": [
      "What's your favorite thing about spending time with grandparents?",
      "What's something you'd like to learn from your grandparent?",
      "What's a family story you'd love to hear more about?",
      "How do you think you're similar to your grandparent?",
      "What's something you want to thank your grandparent for?"
    ],
    "Grandchild": [
      "What's your favorite memory with your grandparent?",
      "What's something special about your relationship?",
      "What have you learned from your grandparent?",
      "What do you love most about family gatherings?",
      "What's something you want to do together?"
    ]
  }
};

export function getRoleSpecificQuestions(relationshipType: string, userRole: string): string[] {
  const questions = roleSpecificQuestions[relationshipType]?.[userRole];
  return questions || [];
}

export function getGeneralRelationshipQuestions(relationshipType: string): string[] {
  // Fallback to general questions if specific role questions aren't available
  const generalQuestions = {
    "Parent-Child": [
      "What's one thing you're grateful for about our relationship?",
      "What's a favorite family tradition?",
      "How do you think we've grown together?",
      "What's something you'd like to do together soon?",
      "What makes our relationship special?"
    ],
    "Romantic Partners": [
      "What's your favorite thing about us as a couple?",
      "What's a dream you have for our future?",
      "How do we make each other better?",
      "What's your favorite memory together?",
      "What makes you feel most loved?"
    ],
    "Friends": [
      "What's the best part of our friendship?",
      "How have we supported each other?",
      "What adventure should we go on next?",
      "What's something you admire about me?",
      "What makes our friendship unique?"
    ],
    "Siblings": [
      "What's your favorite childhood memory together?",
      "How have we influenced each other?",
      "What family trait do we both share?",
      "What's something you appreciate about our relationship?",
      "What tradition should we continue?"
    ],
    "Grandparents": [
      "What's your favorite family story?",
      "What wisdom would you like to share?",
      "How has our family changed over the years?",
      "What's your proudest family moment?",
      "What do you hope for our family's future?"
    ]
  };
  
  return generalQuestions[relationshipType as keyof typeof generalQuestions] || [];
}